# Generated by Django 4.0.3 on 2022-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_First_Name', models.CharField(blank=True, max_length=50)),
                ('Customer_Last_Name', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Phone', models.IntegerField(blank=True)),
                ('Address', models.CharField(blank=True, max_length=300)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('Pincode', models.IntegerField(blank=True)),
                ('State', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
