# Generated by Django 4.0.3 on 2022-03-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='Status',
        ),
    ]
