# Generated by Django 4.0.3 on 2022-03-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_orders_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_Name', models.CharField(blank=True, max_length=50)),
                ('last_Name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('pincode', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('is_paying_customer', models.BooleanField()),
                ('avatar_url', models.URLField(blank=True, max_length=300)),
                ('date_created_gmt', models.DateField()),
                ('date_modified_gmt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Line_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('variation_id', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('tax_class', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.FloatField(blank=True)),
                ('subtotal_tax', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('total_tax', models.FloatField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers')),
            ],
        ),
        migrations.CreateModel(
            name='ordersssss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('order_key', models.CharField(blank=True, max_length=200)),
                ('created_via', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_method_title', models.CharField(blank=True, max_length=70)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('date_paid_gmt', models.DateField()),
                ('discount_total', models.FloatField(blank=True)),
                ('discount_tax', models.FloatField(blank=True)),
                ('shipping_tax', models.FloatField(blank=True)),
                ('shipping_total', models.FloatField(blank=True)),
                ('total_tax', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('date_created', models.DateField()),
                ('date_modified_gmt', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers')),
                ('line_items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.line_items')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.AddField(
            model_name='line_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products'),
        ),
    ]
