# Generated by Django 4.0.3 on 2022-03-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_customers_line_items_ordersssss_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ordersssss',
            new_name='Orders',
        ),
    ]
