# Generated by Django 4.0.3 on 2022-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_ordersssss_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_modified_gmt',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_paid_gmt',
            field=models.DateField(blank=True),
        ),
    ]
