# Generated by Django 4.0.3 on 2022-03-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_orders_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='line_items',
        ),
    ]
