# Generated by Django 4.0.3 on 2022-03-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_orders_customer_id_orders_line_items_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('slug', models.URLField(blank=True, max_length=300)),
                ('permalink', models.URLField(blank=True, max_length=300)),
                ('date_created_gmt', models.DateField(blank=True)),
                ('date_modified_gmt', models.DateField(blank=True)),
                ('type', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('featured', models.BooleanField()),
                ('catalog_visibility', models.CharField(blank=True, max_length=40)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('regular_price', models.CharField(blank=True, max_length=40)),
                ('sale_price', models.CharField(blank=True, max_length=40)),
                ('date_on_sale_from_gmt', models.DateField(blank=True)),
                ('date_on_sale_to_gmt', models.DateField(blank=True)),
                ('on_sale', models.BooleanField()),
                ('price_html', models.CharField(blank=True, max_length=40)),
                ('purchasable', models.BooleanField(blank=True)),
                ('total_sales', models.IntegerField(blank=True)),
                ('downloadable', models.BooleanField(blank=True)),
                ('tax_status', models.CharField(blank=True, max_length=40)),
                ('stock_quantity', models.IntegerField(blank=True)),
                ('backorders', models.CharField(blank=True, max_length=40)),
                ('backorders_allowed', models.BooleanField(blank=True)),
                ('backordered', models.BooleanField(blank=True)),
                ('manage_stock', models.BooleanField(blank=True)),
                ('stock_status', models.CharField(blank=True, max_length=40)),
                ('sold_individually', models.BooleanField(blank=True)),
                ('weight', models.CharField(blank=True, max_length=40)),
                ('average_rating', models.CharField(blank=True, max_length=40)),
                ('reviews_allowed', models.BooleanField(blank=True)),
                ('rating_count', models.IntegerField(blank=True)),
                ('categories', models.IntegerField(blank=True)),
                ('images', models.IntegerField(blank=True)),
                ('attributes', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='line_items',
            name='product',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
