# Generated by Django 4.0.3 on 2022-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_product_alter_line_items_product_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
