# Generated by Django 4.0.3 on 2022-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
