# Generated by Django 4.0.3 on 2022-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
