# Generated by Django 4.0.3 on 2022-03-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_alter_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.categories')),
            ],
        ),
    ]
