# Generated by Django 4.0.3 on 2022-03-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_categories',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products'),
        ),
    ]
