# Generated by Django 4.0.3 on 2022-03-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_alter_product_categories_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Attributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attributes_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.attributes')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products')),
            ],
        ),
    ]
