# Generated by Django 4.0.3 on 2022-03-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_alter_products_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created_gmt', models.DateField(blank=True)),
                ('src', models.CharField(blank=True, max_length=200)),
                ('date_modified_gmt', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='attributes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.product_attributes'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True)),
                ('date_created_gmt', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('reviewer', models.CharField(blank=True, max_length=100)),
                ('reviewer_email', models.CharField(blank=True, max_length=100)),
                ('review', models.CharField(blank=True, max_length=200)),
                ('rating', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Product_reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products')),
                ('reviews_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.reviews')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.product_images'),
        ),
    ]
