# Generated by Django 4.0.3 on 2022-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_images_alter_products_attributes_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='customer_id',
            field=models.IntegerField(blank=True),
        ),
    ]
