# Generated by Django 4.0.3 on 2022-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_remove_reviews_name_remove_reviews_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
