# Generated by Django 4.0.3 on 2022-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='permalink',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
