# Generated by Django 4.0.3 on 2022-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_alter_products_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='attributes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.IntegerField(blank=True),
        ),
    ]
