# Generated by Django 4.0.3 on 2022-03-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_remove_line_items_p_id_line_items_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.IntegerField(blank=True)),
                ('product_id', models.IntegerField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('variation_id', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('tax_class', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.FloatField(blank=True)),
                ('subtotal_tax', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('total_tax', models.FloatField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('customer_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers')),
            ],
        ),
        migrations.DeleteModel(
            name='Line_items',
        ),
    ]
