# Generated by Django 4.0.3 on 2022-03-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_line_items_delete_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_items',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
