# Generated by Django 4.0.3 on 2022-03-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_rename_customer_id_line_items_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_items',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.orders'),
            preserve_default=False,
        ),
    ]
