# Generated by Django 4.0.3 on 2022-03-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_line_items_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='line_items',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers'),
        ),
        migrations.AlterField(
            model_name='line_items',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.orders'),
        ),
    ]
