# Generated by Django 4.0.3 on 2022-03-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_alter_products_attributes_alter_products_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_items',
            old_name='p_id',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='line_items',
            name='customer_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers'),
        ),
    ]
