# Generated by Django 4.0.3 on 2022-03-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_alter_products_attributes_alter_products_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_items',
            name='p_id',
        ),
        migrations.AddField(
            model_name='line_items',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products'),
            preserve_default=False,
        ),
    ]
