# Generated by Django 4.0.3 on 2022-03-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_remove_line_items_p_id_line_items_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line_items',
        ),
    ]
