# Generated by Django 4.0.3 on 2022-03-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_line_item_delete_line_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('variation_id', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('tax_class', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.FloatField(blank=True)),
                ('subtotal_tax', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('total_tax', models.FloatField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.products')),
            ],
        ),
        migrations.DeleteModel(
            name='Line_item',
        ),
    ]
