# Generated by Django 4.0.3 on 2022-03-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_line_items_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers'),
            preserve_default=False,
        ),
    ]
