# Generated by Django 4.0.3 on 2022-03-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_remove_line_items_customer_line_items_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line_items',
        ),
    ]
