# Generated by Django 4.0.3 on 2022-03-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_orders_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cust',
        ),
        migrations.AddField(
            model_name='orders',
            name='c',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
