# Generated by Django 4.0.3 on 2022-03-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_remove_orders_customer_id_orders_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='cust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
