# Generated by Django 4.0.3 on 2022-03-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0033_remove_orders_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
    ]
