# Generated by Django 4.0.3 on 2022-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0036_alter_line_items_customer_alter_line_items_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.IntegerField(blank=True),
        ),
    ]
